### ISSUE TITLE
Como Proveedor quiero poder registrarme en BAFix

### ISSUE THREAD

**Issue by tbotalla** [fiubyte/.github#1]
Como proveedor de servicios
Quiero poder registrarme en BA Fix
Para poder dar de alta mis servicios y recibir clientes

**Criterios de aceptación:**

**Escenario 1:** Redireccion al formulario de registro
Dado que un proveedor ingresa a la web de BA Fix por primera vez
Y hace click en "Registrar" 
Entonces visualiza un formulario de registro
![E1](https://github.com/fiubyte/.github/assets/62850802/a8477841-73f6-4dbf-909a-ff51beceb2e3)

**Escenario 2:** Registro de datos del proveedor exitoso
Dado que un proveedor ingresa al formulario de registro de BA Fix
Y ingresa su nombre y apellido
Y ingresa su DNI
Y ingresa su calle, numero y codigo postal
Y ingresa su teléfono
Y ingresa su correo electronico
Y ingresa su contraseña
Y ingresa la confirmación de contraseña
Y ingresa el link de su foto de perfil
Y ingresa su distancia máxima
Cuando presiona en "Finalizar registro"
Entonces el proveedor es redirigido al inicio de la web 
Y se muestra un mensaje de "Usuario registrado con exito"
![E2](https://github.com/fiubyte/.github/assets/62850802/c111e9e0-6792-4eb4-a547-6ecc22e5d5c6)

**Escenario 3:** Registro fallido por error backend
Dado que un proveedor ingresa al formulario de registro de BA Fix
Y ingresa todos sus datos 
Y el servicio backend esta caído
Cuando presiona en "Finalizar registro"
Entonces el usuario es redirigido a la pantalla anterior 
Y se muestra un error con "Error al registrarse"
![E3](https://github.com/fiubyte/.github/assets/62850802/8eb549b5-0db5-43a7-bab2-de6672bb606b)

**Escenario 4:** Registro fallido por omision de campo
Dado que un proveedor ingresa al formulario de registro de BA Fix
Y ingresa todos sus datos personales menos el email
Cuando presiona en "Finalizar registro"
Entonces se muestra al lado del campo de correo electronico un mensaje que dice "Campo obligatorio" 
Y se muestra un error que dice "Error al completar registro, revise los campos indicados"
![E4](https://github.com/fiubyte/.github/assets/62850802/0f122a75-53f5-4650-9855-3f48d5eb6854)

**Escenario 5:** Nombre invalido
Dado que un proveedor ingresa al formulario de registro de BA Fix
E intenta ingresar caracteres no alfabeticos en el campo "Nombre"
Entonces no se escribe nada en el campo "Nombre"

**Escenario 6:** Nombre demasiado largo
Dado que un proveedor ingresa al formulario de registro de BA Fix
E intenta ingresar mas de 30 caracteres en el campo "Nombre"
Entonces no se escribe nada en el campo "Nombre"

**Escenario 7:** Apelido invalido
Dado que un proveedor ingresa al formulario de registro de BA Fix
E intenta ingresar caracteres no alfabeticos en el campo "Apellido"
Entonces no se escribe nada en el campo "Apellido"

**Escenario 8:** Apellido demasiado largo
Dado que un proveedor ingresa al formulario de registro de BA Fix
E intenta ingresar mas de 20 caracteres en el campo "Apellido"
Entonces no se escribe nada en el campo "Apellido"

**Escenario 9:** DNI invalido
Dado que un proveedor ingresa al formulario de registro de BA Fix
E intenta ingresar caracteres no numericos en el campo "DNI"
Entonces no se escribe nada en el campo "DNI"

**Escenario 10:** Codigo postal invalido
Dado que un proveedor ingresa al formulario de registro de BA Fix
E intenta ingresar caracteres no numericos en el campo "Código Postal"
Entonces no se escribe nada en el campo "Código Postal"

**Escenario 11:** Numero invalido
Dado que un proveedor ingresa al formulario de registro de BA Fix
E intenta ingresar caracteres no numericos en el campo "Numero"
Entonces no se escribe nada en el campo "Numero"

**Escenario 12:** Telefono invalido 
Dado que un proveedor ingresa al formulario de registro de BA Fix
E intenta ingresar caracteres no numericos en el campo "Telefono"
Entonces no se escribe nada en el campo "Telefono"

**Escenario 13:** Correo electronico invalido
Dado que un proveedor ingresa al formulario de registro de BA Fix
E intenta ingresar un correro electronico que no cumple con el formato requerido en el campo "Correo electronico"
Entonces se muestra al lado del campo de correo electronico un mensaje que dice "Correo electronico Invalido"
Y se muestra un error que dice "Error al completar registro, revise los campos indicados"

**Escenario 14:** Contraseña demasiado corta
Dado que un proveedor ingresa al formulario de registro de BA Fix
E intenta ingresar una contraseña de menos de 6 caracteres en el campo "Contraseña"
Entonces se muestra al lado del campo de contraseña un mensaje que dice "Contraseña demasiado corta"
Y se muestra un error que dice "Error al completar registro, revise los campos indicados"

**Escenario 15:** Contraseñas no coinciden
Dado que un proveedor ingresa al formulario de registro de BA Fix
E ingresar una contraseña en el campo "Contraseña"
E ingresar una contraseña en el campo "Confirmacion de Contraseña"
Y ambas contraseñas no coinciden
Entonces se muestra al lado del campo de contraseña un mensaje que dice "Las contraseñas deben coincidir"
Y se muestra un error que dice "Error al completar registro, revise los campos indicados"

**Escenario 16:** Link a foto de perfil invalida
Dado que un proveedor ingresa al formulario de registro de BA Fix
E intenta ingresar un link a su foto de perfil que no cumple con el formato requerido en el campo "Link a foto de perfil"
Entonces se muestra al lado del campo de Link a foto de perfil un mensaje que dice "Link a foto de perfil invalida"
Y se muestra un error que dice "Error al completar registro, revise los campos indicados"

**Comment by crpistillo** [comment]
Comentario de prueba

**Comment by matias-gonz** [comment]
<img width="224" alt="image" src="https://github.com/fiubyte/.github/assets/74241889/f2d321d4-78f6-4abc-822e-eb9ff658b2d0">

@tbotalla hay que actualizar los campos en el backend
