### ISSUE TITLE
Como Usuario quiero poder ver el promedio de calificaciones de los servicios

### ISSUE THREAD

**Issue by matias-gonz** [fiubyte/.github#29]
Como Usuario
Quiero poder ver los comentarios de otros usuarios en un servicio
Para ver si me conviene contratarlo

**Criterios de aceptación:**

**Escenario 1:** Un usuario ingresa al detalle de un Servicio que tiene calificaciones
Dado que un usuario esta visualizando el listado de servicios
Y existe un servicio con calificaciones aprobadas
Cuando el usuario selecciona el servicio
Entonces se visualiza el promedio de calificaciones debajo del titulo del servicio
Y visualiza un boton de "Opiniones" en el menu del detalle del servicio
![E1_ Usuario ingresa al detalle de un Servicio que tiene calificaciones](https://github.com/fiubyte/.github/assets/62850802/05473869-5268-4969-8cd2-8e6b83f58dd4)

**Escenario 2:** Un usuario ingresa al detalle de un Servicio que no tiene calificaciones
Dado que un usuario esta visualizando el listado de servicios
Y existe un servicio sin calificaciones aprobadas
Cuando el usuario selecciona el servicio
Entonces se visualiza un mensaje "No hay opiniones" debajo del titulo del servicio
Y no visualiza un boton de "Opiniones" en el menu del detalle del servicio
![E2_ Un usuario ingresa al detalle de un Servicio que no tiene calificaciones](https://github.com/fiubyte/.github/assets/62850802/cce77aea-31c5-40c0-8dc5-7a0a4ae88c07)
 
**Escenario 3:** Un usuario visualiza calificaciones en la lista de servicios
Dado que existe un servicio con calificaciones aprobadas
Cuando el usuario ingresa al listado de servicios
Entonces visualiza el promedio de calificacioens de ese servicio debajo del titulo del mismo
![E3_ Un usuario visualiza calificaciones en la lista de servicios](https://github.com/fiubyte/.github/assets/62850802/bd2ab79f-4f44-44f4-a481-02d29ba2c5be)

**Escenario 4:** Un usuario visualiza calificaciones en el mapa
Dado que existe un servicio con calificaciones aprobadas
Cuando el usuario ingresa a la visualizacion del mapa de servicios
Y presiona sobre un proveedor en el mapa
Entonces visualiza el promedio de calificaciones de los servicios del proveedor
![E4_ Un usuario visualiza calificaciones en el mapa](https://github.com/fiubyte/.github/assets/62850802/7b6dc7df-4160-408d-bfee-edea4ac62397)

**Escenario 5:** Un usuario visualiza los servicios de la lista cuando el servicio de backend de comentarios esta caido
Dado que un usuario esta visualizando el listado de servicios
Y existen servicios con calificaciones aprobadas
Y el servicio de backend de calificaciones esta caido
Entonces visualiza el mensaje "No hay opiniones" debajo del titulo de cada servicio
![E5_ Un usuario visualiza los servicios de la lista cuando el servicio de backend de comentarios esta caido](https://github.com/fiubyte/.github/assets/62850802/b44be9e3-8c5f-4951-a5a7-a74f1cd8c4cc)

**Escenario 6:** Un usuario visualiza los servicios del mapa cuando el servicio de backend de comentarios esta caido
Dado que un usuario esta visualizando el mapa de servicios
Y existen servicios con calificaciones aprobadas
Y el servicio de backend de calificaciones esta caido
Cuando el usuario selecciona en la ubicacion de un proveedor
Entonces visualiza el mensaje "No hay opiniones" debajo del titulo del proveedor
![E6_ Un usuario visualiza los servicios del mapa cuando el servicio de backend de comentarios esta caido](https://github.com/fiubyte/.github/assets/62850802/653e76b4-06b6-4326-bb21-cc9e4c093dfc)

**Comment by tbotalla** [comment]
DONE backend: added "avg_rate" on GET /services/<id>

**Comment by crpistillo** [comment]
@tbotalla Falta arreglar
- Que el promedio del "service_avg_rate" se calcule bien / de forma consistente. Actualmente hay servicios como el de "Pintura de interiores" que me devuelven un promedio de "1.0" cuando tiene un comentario con "1" y otro con "4"
