### ISSUE TITLE
Como Proveedor quiero ver el promedio de calificaciones de mis servicios

### ISSUE THREAD

**Issue by matias-gonz** [fiubyte/.github#30]
Como Proveedor
Quiero poder ver el promedio de calificaciones de mis servicios
Para poder mejorar mis prestaciones

Criterios de aceptación:

Escenario 1: Visualización de Servicio con calificaciones
Dado un Proveedor ingresa al listado "Mis Servicios"
Y existe al menos uno sus Servicios que recibió calificaciones
Cuando Proveedor selecciona el detalle del Servicio
Entonces puede ver el promedio de calificaciones

![Image](https://github.com/fiubyte/.github/assets/113869142/9f7bebae-4c03-4428-afa1-bb0abfe5f574)

Escenario 2: Visualización de Servicio sin comentarios
Dado un Proveedor ingresa al listado "Mis Servicios"
Y ninguno de sus Servicios que recibió alguna calificacion
Cuando Proveedor selecciona el detalle del Servicio
Entonces puede ver un mensaje "Todavía no hay calificaciones"

![Image](https://github.com/fiubyte/.github/assets/113869142/8d8ba1e3-9301-4b5b-b07f-b5c431bcc363)

**Comment by tbotalla** [comment]
DONE backend
