### ISSUE TITLE
Como Administrador quiero ver la foto del DNI del proveedor

### ISSUE THREAD

**Issue by matias-gonz** [fiubyte/.github#37]
Como Administrador quiero ver la foto del DNI del proveedor 

Criterios de aceptacion:

Escenario 1: El administrador visualiza la imagen de DNI cargada por el proveedor
Dado que el administrador esta en la pagina de un servicio
Cuando presiona Foto de DNI
Entonces visualiza la foto del DNI subida por el proveedor

![E1_ El administrador rechaza Servicio con mensaje(7)](https://github.com/fiubyte/.github/assets/74241889/830943e4-dae5-483f-9763-6f1749e724f8)

Escenario 2: Error en el sistema al visualizar la imagen de DNI
Dado que el administrador esta en la pagina de un servicio
Y presiona en ver "foto DNI"
Cuando ocurre un error en el sistema 
Entonces visualiza un cartel que dice "Ocurrio un error al cargar la identidad del proveedor, intente nuevamente mas tarde"

![E3_ El administrador quiere aprobar una identidad pero hay un error por servicio backend caido(3)](https://github.com/fiubyte/.github/assets/113869142/d70ac84c-3cc8-4f0a-823b-8b4605496315)

**Comment by tbotalla** [comment]
Added "document_photo_url" on response of GET /users/
