### ISSUE TITLE
Como Administrador quiero ver la fecha de solicitud de cada servicio

### ISSUE THREAD

**Issue by matias-gonz** [fiubyte/.github#40]
Escenario 1: El administrador ve la fecha de solicitud de cada servicio
Dado que el administrador esta dentro de la visualizacion de un servicio
Entonces el administrador visualiza la fecha de solicitud de aprobacion del servicio

![#40 Como Administrador quiero ver la fecha de solicitud de cada servicio](https://github.com/fiubyte/.github/assets/113869142/f8a4cac6-5d3f-4471-8745-408a8a99e873)

**Comment by tbotalla** [comment]
DONE backend: added "requested_date" on response
