### ISSUE TITLE
Como Usuario quiero poder marcar un servicio como favorito

### ISSUE THREAD

**Issue by matias-gonz** [fiubyte/.github#42]
Como Usuario
Quiero poder marcar un servicio como favorito
Para que se guarde en mi lista de favoritos

Criterios de aceptación:

**Escenario 1:** Un usuario marca un servicio como favorito
Dado que un usuario se encuentra en la pagina de detalle de un servicio
Y el servicio no se encuentra en su lista de favoritos
Cuando el usuario cliquea en el icono con forma de corazon
Entonces el icono cambia de color y el servicio es guardado en la lista de favoritos del usuario 
Y se visualiza un mensaje que dice "Agregado a favoritos con exito!"
![E1_ Un usuario marca un servicio como favorito (1)](https://github.com/fiubyte/.github/assets/62850802/e0ef3fac-ea2c-44f7-9271-4a8de5279a3f)

**Escenario 2:** Un usuario marca un servicio como favorito pero el backend esta caido
Dado que un usuario se encuentra en la pagina de detalle de un servicio
Y el servicio no se encuentra en su lista de favoritos
Y el backend esta caido
Cuando el usuario cliquea en el icono con forma de corazon
Entonces se visualiza un mensaje de error que dice "Ha ocurrido un error.  Por favor, intenta de nuevo más tarde."
![E2_ Un usuario marca un servicio como favorito pero el backend esta caido](https://github.com/fiubyte/.github/assets/62850802/fbfb4697-1ea8-4d40-bcc5-9f972a73a18c)

**Comment by tbotalla** [comment]
DONE backend: added POST /service/<id>/fav
