### ISSUE TITLE
Como Usuario quiero poder desmarcar un servicio como favorito

### ISSUE THREAD

**Issue by matias-gonz** [fiubyte/.github#43]
Como Usuario
Quiero poder desmarcar un servicio como favorito
Para que se elimine en mi lista de favoritos

Criterios de aceptación:

**Escenario 1**: Un usuario desmarca un servicio como favorito
Dado que un usuario se encuentra en la pagina de detalle de un servicio
Y el servicio se encuentra en su lista de favoritos
Cuando el usuario cliquea en el icono con forma de corazon
Entonces el icono cambia de color y el servicio es eliminado de la lista de favoritos del usuario
Y se visualiza un mensaje que dice "Quitado de favoritos con exito!"
![E1_ Un usuario desmarca un servicio como favorito (1)](https://github.com/fiubyte/.github/assets/62850802/0c38e8d6-da33-47a9-8c15-8db600e93a17)

**Escenario 2:** Un usuario desmarca un servicio como favorito pero el backend esta caido
Dado que un usuario se encuentra en la pagina de detalle de un servicio
Y el servicio se encuentra en su lista de favoritos
Y el backend esta caido
Cuando el usuario cliquea en el icono con forma de corazon
Entonces se visualiza un mensaje de error que dice "Ha ocurrido un error.  Por favor, intenta de nuevo más tarde."
![E2_ Un usuario marca un servicio como favorito pero el backend esta caido (1)](https://github.com/fiubyte/.github/assets/62850802/6e6cbfd3-3eee-4efa-b7af-b7d3675eb365)

**Comment by tbotalla** [comment]
DONE backend: added POST /service/<id>/unfav
