### ISSUE TITLE
Como Usuario quiero poder ver mis servicios favoritos

### ISSUE THREAD

**Issue by matias-gonz** [fiubyte/.github#44]
Como Usuario
Quiero poder ver mis servicios favoritos
Para poder tener acceso rapido a los mismos

Criterios de aceptación:

**Escenario 1:** Un usuario visualiza su lista de favoritos
Dado que un usuario ha guardado 3 servicios en su lista de favoritos
Y el usuario se encuentra en cualquier lugar de la app
Cuando el usuario presiona en el boton del menu principal
Y luego presiona en "Favoritos"
Entonces visualiza una lista que contiene sus servicios marcados como favoritos
![E1_ Un usuario visualiza su lista de favoritos](https://github.com/fiubyte/.github/assets/62850802/e15222c2-6c02-42dd-8e48-c5f0eb2e1fd0)

**Escenario 2:** Un usuario visualiza su lista de favoritos pero no tiene servicios favoritos agregados
Dado que un usuario no ha guardado ningun servicio en su lista de favoritos
Y el usuario se encuentra en cualquier lugar de la app
Cuando el usuario presiona en el boton del menu principal
Y luego presiona en "Favoritos"
Entonces visualiza un mensaje que dice "Aún no tienes servicios agregados como “Favoritos”. "
![E2_ Un usuario visualiza su lista de favoritos pero no tiene servicios favoritos agregados](https://github.com/fiubyte/.github/assets/62850802/374396a3-9f63-486b-a8ee-8cf8ce422076)

**Escenario** 3: Un usuario visualiza su lista de favoritos pero el backend esta caido
Dado que un usuario ha guardado 3 servicios en su lista de favoritos
Y el usuario se encuentra en cualquier lugar de la app
Y el servicio de backend esta caido
Cuando el usuario presiona en el boton del menu principal
Y luego presiona en "Favoritos"
Entonces visualiza un mensaje de error que dice "Ha ocurrido un error. Por favor, intenta de nuevo más tarde."
![E3_ Un usuario visualiza su lista de favoritos pero el backend esta caido](https://github.com/fiubyte/.github/assets/62850802/9c3dfc6a-61d6-4ec6-bc21-4a236836029c)

**Comment by tbotalla** [comment]
DONE backend: added flag "faved_only" on GET /services/filter. Also added "faved_by_me" on response
